'''It's time to open the store with your newly renovated inventory system! To start, create a new file called sales.py, and in it create a function called generate_computers.


This function should generate 3-5 computers and 3-5 laptops. All of the specs should comply with the ranges given in context above. These 6-10 machines should be returned in a list.


Create a second function called sell_computers. This function should take in the list generated by the previous function, and randomly select some subset of it to be 'sold'. The function should then print out a report of the average stats of sold computers and unsold computers.'''


from comps import *
from random import randint, sample


def generate_computers():
    comps = randint(3, 5)
    laps = randint(3, 5)


if __name__ == '__main__':
    generate_computers()
